### ISSUE TITLE
VPN support for Huawei EG8145V.

### ISSUE THREAD

**Issue by avc1657** [Huawei-LTE-routers-mods/README#3]
Hi, i'd like to have vpn support for my huawei router. Btw I'm new to this "custom firmware installing" so i'd like to ask if this github repo is the right place or not. Maybe i'm getting things wrong, idk, like i said im new to these things.

**Comment by ValdikSS** [comment]
Your router is based on completely different architecture. This firmware is only for LTE modems/routers, it's not suitable for it.
